language: node_js

node_js:
  - stable

install:
  - npm install

before_script: chmod 0777 ./node_modules/.bin/mocha

script:
  - npm test
  - npm run cover

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"